version: '3.8'

services:
  gm-facematch-engine:
    build: .
    container_name: gm-facematch-Engine-container
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      PORT: 5005  # Set the PORT environment variable here
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: gm-facematch-engine-postgres-container
    environment:
      POSTGRES_DB: facematch-engine-db
      POSTGRES_USER: engineuser
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  default:
    external:
      name: gm-services-docker-network

volumes:
  db_data:
